name: Deploy to Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-to-main
  cancel-in-progress: true

jobs:
  test:
    name: Test Deployment Job
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12'
          cache: 'npm'

      - name: Update npm
        run: npm install -g npm@9.2.0

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm config set engine-strict false; npm install --legacy-peer-deps --ignore-scripts

      - name: Build pagefind manually
        run: node node_modules/pagefind/lib/postinstall.js
        continue-on-error: true

      - name: Run linting
        run: npm run lint:all

      - name: Run all scripts in script/
        shell: pwsh
        run: |
          $scripts = Get-ChildItem -Path "script" -Filter "*.js"
          foreach ($script in $scripts) {
            Write-Host "Running $($script.Name)" -ForegroundColor Cyan
            node $script.FullName
            if ($LASTEXITCODE -ne 0) {
              throw "Script $($script.Name) failed with exit code $LASTEXITCODE"
            }
          }

      #- name: URL Checker with timeout
      #  run: node script/url-checker.js ${{ vars.URL_CHECKER_TIMEOUT }}

  build:
    name: Build Job
    runs-on: self-hosted
    needs: [test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Configure Pages
      #  uses: actions/configure-pages@v4

      #- name: Set up Node.js
       # uses: actions/setup-node@v3
        #with:
        #  node-version: '18'

      #- name: Cache Node modules
       # uses: actions/cache@v3
        #with:
         # path: ~/.npm
          #key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          #restore-keys: |
           # ${{ runner.os }}-node-

      #- name: Install dependencies
       # run: npm install

  deploy:
    name: Deploy Job
    runs-on: self-hosted
    needs: [test, build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Deploy Application
       # run: |
        #  echo "Starting deployment..."
         # scp -r ./build user@server:/var/www/html
          #echo "Application deployed successfully."
